name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build all
      run: build all
      shell: cmd
      working-directory: ./rogue

